# Generated by Django 4.2.6 on 2023-10-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.DateTimeField(blank=True, null=True, verbose_name='время рассылки')),
                ('periodicity', models.DateTimeField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], verbose_name='периодичность')),
                ('mailing_status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], max_length=100, verbose_name='статус рассылки')),
                ('recipient', models.ManyToManyField(related_name='newsletters', to='client.client', verbose_name='получатели')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='тема письма')),
                ('content', models.TextField(verbose_name='тело письма')),
                ('newsletter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.newsletter', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата попытки')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='время попытки')),
                ('attempt_status', models.BooleanField(default=False, verbose_name='статус попытки')),
                ('server_response', models.TextField(verbose_name='ответ сервера')),
                ('message', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='message.mailingmessage', verbose_name='письмо')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='message.newsletter', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог рассылки',
                'verbose_name_plural': 'логи рассылок',
            },
        ),
    ]
