# Generated by Django 4.2.6 on 2023-10-08 16:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='тема письма')),
                ('content', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'сообщение для рассылки',
                'verbose_name_plural': 'сообщения для рассылки',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.DateTimeField(blank=True, null=True, verbose_name='время рассылки')),
                ('periodicity', models.DurationField(choices=[(datetime.timedelta(days=1), 'Ежедневно'), (datetime.timedelta(days=7), 'Еженедельно'), (datetime.timedelta(days=30, seconds=43200), 'Ежемесячно')], max_length=20, verbose_name='периодичность')),
                ('mailing_status', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], max_length=100, verbose_name='статус рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='message.mailingmessage', verbose_name='сообщение')),
                ('recipients', models.ManyToManyField(related_name='newsletters', to='client.client', verbose_name='получатели')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата попытки')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='время попытки')),
                ('success', models.BooleanField(default=False, verbose_name='успешность попытки')),
                ('server_response', models.TextField(blank=True, verbose_name='ответ сервера')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='message.newsletter', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог рассылки',
                'verbose_name_plural': 'логи рассылки',
            },
        ),
    ]
