# Generated by Django 4.2.6 on 2023-10-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='newsletter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='message.newsletter', verbose_name='рассылка'),
        ),
    ]
