# Generated by Django 4.2.6 on 2023-10-12 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_logs', to='client.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='mailingmessage',
            name='status',
            field=models.CharField(choices=[('К отправке', 'К отправке'), ('Отправлено', 'Отправлено')], default='К отправке', max_length=50, verbose_name='статус отправки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='mailing_status',
            field=models.CharField(choices=[('Завершена', 'Завершена'), ('Создана', 'Создана'), ('Запущена', 'Запущена')], default='Создана', max_length=100, verbose_name='статус рассылки'),
        ),
    ]
