# Generated by Django 4.2.6 on 2023-10-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'verbose_name': 'лог рассылки', 'verbose_name_plural': 'лог рассылок'},
        ),
    ]
