# Generated by Django 4.2.6 on 2023-10-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_mailingmessage_newsletter_newsletter_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingmessage',
            name='newsletter',
        ),
    ]
