# Generated by Django 4.2.6 on 2023-10-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_mailinglog_client_alter_mailingmessage_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='message',
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='newsletter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.newsletter', verbose_name='рассылка'),
        ),
    ]
