# Generated by Django 4.2.6 on 2023-10-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_newsletter_message_mailingmessage_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'verbose_name': 'лог', 'verbose_name_plural': 'логи'},
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='status',
            field=models.CharField(choices=[('ok', 'Успешно'), ('failed', 'Ошибка')], default='Успешно', max_length=20, verbose_name='статус'),
        ),
    ]
