# Generated by Django 4.2.6 on 2023-10-09 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_mailinglog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='mailing_status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=100, verbose_name='статус рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.DurationField(choices=[(datetime.timedelta(days=1), 'Ежедневно'), (datetime.timedelta(days=7), 'Еженедельно'), (datetime.timedelta(days=30, seconds=43200), 'Ежемесячно')], default=datetime.timedelta(days=1), max_length=20, verbose_name='периодичность'),
        ),
    ]
