# Generated by Django 4.2.6 on 2023-10-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_newsletter_mailing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='message.newsletter', verbose_name='рассылка'),
        ),
    ]
