# Generated by Django 4.2.6 on 2023-10-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('is_active', 'Can block user')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
