# Generated by Django 4.2.6 on 2023-10-11 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_mailinglog_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 12, 31), verbose_name='дата окончания рассылки'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 12, 31), verbose_name='дата начала рассылки'),
        ),
    ]
