# Generated by Django 4.2.6 on 2023-10-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
