# Generated by Django 4.2.6 on 2023-10-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_newsletter_end_date_newsletter_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmessage',
            name='status',
            field=models.CharField(choices=[('К отправке', 'отправить'), ('Отправлено', 'Отправлено')], default='К отправке', max_length=50, verbose_name='статус отправки'),
        ),
    ]
