# Generated by Django 4.2.6 on 2023-10-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_alter_newsletter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingmessage',
            name='newsletter',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
