# Generated by Django 4.2.6 on 2023-10-11 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_mailingmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 10, 11), verbose_name='дата начала рассылки'),
        ),
    ]
