# Generated by Django 4.2.6 on 2023-10-11 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_alter_newsletter_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата начала рассылки'),
        ),
    ]
