# Generated by Django 4.2.6 on 2023-10-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_alter_newsletter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingmessage',
            name='newsletter',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='messages',
            field=models.ManyToManyField(related_name='newsletters', to='message.mailingmessage', verbose_name='сообщения'),
        ),
    ]
