# Generated by Django 4.2.6 on 2023-10-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='проверочный код'),
        ),
    ]
